name: CI/CD Pipeline

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build (stub)
      run: |
        echo "This is a stub build step."
        # Для настоящей сборки раскомментируй:
        # cd user-service
        # go build -o userService ./cmd/main.go

    - name: Run tests (stub)
      run: echo "No tests configured, skipping."

    - name: Success message
      run: echo "CI pipeline finished successfully!"
