name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build user service
        working-directory: ./user-service
        run: go build -o userService ./cmd/main.go

      - name: Run tests
        run: go test ./user-service/internal/infrastructure/repositories


